#!/bin/sh

CURRENT_DATE_FILENAME=$( date +%Y%m%d_%H%M%S )

ssh nrpm@niederrhein.pm.org "( mkdir ~/deployment/new-nrpm-web )"
scp $1 nrpm@niederrhein.pm.org:~/deployment/new-nrpm-web
ssh -t nrpm@niederrhein.pm.org "(
	eval \$(perl -I\$HOME/perl5/lib/perl5 -Mlocal::lib) &&
	cd ~/deployment/new-nrpm-web &&
	tar xz --strip-components=1 -f $1 &&
	rm $1 &&
	cpanm --installdeps . &&
	if [ -f ~/prod/nrpm.web.pid ]; then kill \$( cat ~/prod/nrpm.web.pid ); fi &&
	mv ~/prod/nrpm-web ~/backup/nrpm-web-$CURRENT_DATE_FILENAME &&
	mv ~/deployment/new-nrpm-web ~/prod/nrpm-web &&
	cd ~/prod/nrpm-web &&
	script/nrpm_web_fastcgi.pl --listen ~/prod/nrpm.web.socket -d -p ~/prod/nrpm.web.pid
)"
